// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzzPaLnZ4jftbqpmOlMPclC5fgp2rEHvw',
    appId: '1:1068394481707:web:6df5f10e91445f6dce426e',
    messagingSenderId: '1068394481707',
    projectId: 'bookapp-3f431',
    authDomain: 'bookapp-3f431.firebaseapp.com',
    databaseURL: 'https://bookapp-3f431-default-rtdb.firebaseio.com',
    storageBucket: 'bookapp-3f431.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC40kcOJZEltBjhOjedhcCWnJu0dzmjsLo',
    appId: '1:1068394481707:android:7a9c86691d102e14ce426e',
    messagingSenderId: '1068394481707',
    projectId: 'bookapp-3f431',
    databaseURL: 'https://bookapp-3f431-default-rtdb.firebaseio.com',
    storageBucket: 'bookapp-3f431.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsR14jfqyCv0gQppIdZhI2pSEB3tuOqH8',
    appId: '1:1068394481707:ios:076ea562ed842ab8ce426e',
    messagingSenderId: '1068394481707',
    projectId: 'bookapp-3f431',
    databaseURL: 'https://bookapp-3f431-default-rtdb.firebaseio.com',
    storageBucket: 'bookapp-3f431.appspot.com',
    iosClientId: '1068394481707-0fg1r2odvnmofq51v1l55fphu03rftg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.readx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsR14jfqyCv0gQppIdZhI2pSEB3tuOqH8',
    appId: '1:1068394481707:ios:076ea562ed842ab8ce426e',
    messagingSenderId: '1068394481707',
    projectId: 'bookapp-3f431',
    databaseURL: 'https://bookapp-3f431-default-rtdb.firebaseio.com',
    storageBucket: 'bookapp-3f431.appspot.com',
    iosClientId: '1068394481707-0fg1r2odvnmofq51v1l55fphu03rftg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.readx',
  );
}
